---
apiVersion: v1
kind: ImageStream
metadata:
  name: ovms-faster-rcnn-resnet101-coco-sparse-60-0001
  labels:
    application: ovms-faster-rcnn-resnet101-coco-sparse-60-0001
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ovms-faster-rcnn-resnet101-coco-sparse-60-0001
spec:
  triggers:
    - type: "ConfigChange"
  lookupPolicy:
    local: true
  output:
    to:
      kind: ImageStreamTag
      name: ovms-faster-rcnn-resnet101-coco-sparse-60-0001:local-build
  source: 
    git:
      uri: https://github.com/mmgaggle/ovms-model
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: openvino/model_server:latest
      env:
      - name: ZOO_BASE
        value: https://storage.openvinotoolkit.org/repositories/open_model_zoo/2021.3/models_bin
      - name: MODEL
        value: faster-rcnn-resnet101-coco-sparse-60-0001
      - name: VERSION
        value: 2
      - name: PRECISION
        value: FP16

