---
apiVersion: v1
kind: ImageStream
metadata:
  name: ovms-faster-rcnn-resnet101-coco-sparse-60-0001
  labels:
    application: ovms-faster-rcnn-resnet101-coco-sparse-60-0001
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ovms-faster-rcnn-resnet101-coco-sparse-60-0001
spec:
  triggers:
    - type: "ConfigChange"
  lookupPolicy:
    local: true
  output:
    to:
      kind: ImageStreamTag
      name: ovms-faster-rcnn-resnet101-coco-sparse-60-0001:local-build
  source: 
    git:
      uri: https://github.com/mmgaggle/ovms-model
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: openvino/model_server:latest
      configMaps:
        - configMap:
            name: ovms-pipeline
          destinationDir: ".pipeline"
